// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-AUxlEBBUIl5Hsqs82p-V2v9o1tfZIbw',
    appId: '1:562194623173:web:a2fcbb97b40a7bb66d5eac',
    messagingSenderId: '562194623173',
    projectId: 'stepmd-ebcd9',
    authDomain: 'stepmd-ebcd9.firebaseapp.com',
    storageBucket: 'stepmd-ebcd9.appspot.com',
    measurementId: 'G-FNB4FM5CWM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsTb_Ny_E0Zv0ntCpk6LvwC3h25CLgAeY',
    appId: '1:562194623173:android:de0afe5f3b4b4e166d5eac',
    messagingSenderId: '562194623173',
    projectId: 'stepmd-ebcd9',
    storageBucket: 'stepmd-ebcd9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIRsBCcjcbkcof0PiU-svZt_cH8uu5GXY',
    appId: '1:562194623173:ios:002ca38bbe49dab26d5eac',
    messagingSenderId: '562194623173',
    projectId: 'stepmd-ebcd9',
    storageBucket: 'stepmd-ebcd9.appspot.com',
    iosClientId: '562194623173-iskh90gkaffj10mnd3i36ov2a6upegum.apps.googleusercontent.com',
    iosBundleId: 'com.stepmd.stepmd',
  );
}
